version: '3.8'

services:
    nestjs_api:
        build:
            context: .
            target: dev
        ports:
            - '3000:3000'
            - '9229:9229'
        environment:
            PORT: 3000
            NODE_ENV: development
            SECRET_KEY: /run/secrets/secret_key
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD_FILE: /run/secrets/db_password
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_HOST: mysql_db
            DATABASE_PORT: 3306
            DATABASE_TYPE: ${DATABASE_TYPE}
            CLOUDINARY_NAME: ${CLOUDINARY_NAME}
            CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
            CLOUDINARY_API_SECRET: /run/secrets/cloud_api_secret
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAILDEV_INCOMING_USER: ${MAILDEV_INCOMING_USER}
            MAILDEV_INCOMING_PASS: /run/secrets/mail_pass
            MAIL_SENDER: ${MAIL_SENDER}
            MAIL_SERVICE: ${MAIL_SERVICE}
        secrets:
            - secret_key
            - db_password
            - cloud_api_secret
            - mail_pass
        volumes:
            - ./src:/usr/src/app/src
        depends_on:
            - mysql_db

    mysql_db:
        image: mysql:latest
        ports:
            - '3307:3306'
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD_FILE=/run/secrets/db_password
        secrets:
            - db_root_password
            - db_password
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:

secrets:
    secret_key:
        file: ./run/secrets/secret_key.txt
    db_root_password:
        file: ./run/secrets/db_root_password.txt
    db_password:
        file: ./run/secrets/db_password.txt
    cloud_api_secret:
        file: ./run/secrets/cloud_api_secret.txt
    mail_pass:
        file: ./run/secrets/mail_pass.txt
